apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
  namespace: argocd
  labels:
    app: todo-app
spec:
  replicas: 30
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app-container
        image: joelplush/todo-app:v4
        ports:
        - containerPort: 80
