apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
  namespace : argocd
spec:
  selector:
    app: todo-app

  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
